## **Bag of words**

In [ ]:
import numpy as np
import pandas as pd

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
#vocabulary
print(cv.vocabulary_)

{'people': 2, 'watch': 3, 'dswithbappy': 1, 'write': 4, 'comment': 0}


In [ ]:
bow.toarray()

array([[0, 1, 1, 1, 0],
       [0, 2, 0, 1, 0],
       [1, 0, 1, 0, 1],
       [1, 1, 0, 0, 1]])

In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 1 1 1 0]]
[[0 2 0 1 0]]
[[1 0 1 0 1]]


In [ ]:
# new
cv.transform(['Bappy watch dswithbappy']).toarray()

array([[0, 1, 0, 1, 0]])

In [ ]:
X = bow.toarray()
y = df['output']

In [ ]:
df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

## **N-Gram (here you consider n words as 1 token)**

In [ ]:
df = pd.DataFrame({"text":["people watch dswithbappy",
                         "dswithbappy watch dswithbappy",
                         "people write comment",
                          "dswithbappy write comment"],"output":[1,1,0,0]})

df

text  output
0       people watch dswithbappy       1
1  dswithbappy watch dswithbappy       1
2           people write comment       0
3      dswithbappy write comment       0

In [ ]:
# BI grams (because nggram_range = 2)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(2,2))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch': 2, 'watch dswithbappy': 4, 'dswithbappy watch': 0, 'people write': 3, 'write comment': 5, 'dswithbappy write': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0 1 0]]
[[1 0 0 0 1 0]]
[[0 0 0 1 0 1]]


In [ ]:
#Ti gram
# BI grams
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(ngram_range=(3,3))

In [ ]:
bow = cv.fit_transform(df['text'])

In [ ]:
print(cv.vocabulary_)

{'people watch dswithbappy': 2, 'dswithbappy watch dswithbappy': 0, 'people write comment': 3, 'dswithbappy write comment': 1}


In [ ]:
print(bow[0].toarray())
print(bow[1].toarray())
print(bow[2].toarray())

[[0 0 1 0]]
[[1 0 0 0]]
[[0 0 0 1]]


## **TF-IDF**

In [ ]:
df = pd.DataFrame({"text":["my name is riyan",
                         "people watch riyan",
                         "hello guys welcome me",
                          "welcome riyan welcome"],"output":[1,1,0,0]})

df

text  output
0       my name is riyan       1
1     people watch riyan       1
2  hello guys welcome me       0
3  welcome riyan welcome       0

In [ ]:
from nltk.corpus import stopwords
import nltk
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


True

In [ ]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [ ]:
df['text'] = df['text'].apply(remove_stopwords)

In [ ]:
df.head()

text  output
0            name  riyan       1
1     people watch riyan       1
2    hello guys welcome        0
3  welcome riyan welcome       0

In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer
tfid = TfidfVectorizer()

In [ ]:
arr = tfid.fit_transform(df['text']).toarray()

In [ ]:
arr

array([[0.        , 0.        , 0.84292635, 0.        , 0.53802897,
        0.        , 0.        ],
       [0.        , 0.        , 0.        , 0.64450299, 0.41137791,
        0.64450299, 0.        ],
       [0.61761437, 0.61761437, 0.        , 0.        , 0.        ,
        0.        , 0.48693426],
       [0.        , 0.        , 0.        , 0.        , 0.3752176 ,
        0.        , 0.92693676]])

In [ ]:
print(tfid.idf_)

[1.91629073 1.91629073 1.91629073 1.91629073 1.22314355 1.91629073
 1.51082562]


## Using Advnace deep learning techniques -> Word2vec

In [ ]:
import numpy as np
import pandas as pd
import os
import gensim

In [ ]:
!pip install --upgrade gensim --user

In [ ]:
from nltk import sent_tokenize
from gensim.utils import simple_preprocess
import nltk
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.


True

In [22]:
import os
from nltk.tokenize import sent_tokenize
from gensim.utils import simple_preprocess

story = []
folder_path = '/content/drive/MyDrive/GenerativeAINotebooks/datasets/game_of_thrones'

for filename in os.listdir(folder_path):
    if filename.endswith('.txt'):
        file_path = os.path.join(folder_path, filename)
        try:
            with open(file_path, 'r', encoding='utf-8') as f:
                corpus = f.read()
        except UnicodeDecodeError:
            with open(file_path, 'r', encoding='latin-1') as f:
                corpus = f.read()
        raw_sent = sent_tokenize(corpus)
        for sent in raw_sent:
            story.append(simple_preprocess(sent))

print(f"Total sentences collected: {len(story)}")


Total sentences collected: 145020


In [ ]:

story

In [ ]:
len(story)

27244

In [ ]:
story[0]

In [54]:
model = gensim.models.Word2Vec(
    window=10
    min_count=2 # words that appear less than 2 times in my documents will be ignored
)

In [55]:
model.build_vocab(story)

In [56]:
model.train(story, total_examples=model.corpus_count , epochs=model.epochs)
# total+examples Number of “sentences” to train on (auto-calculated).
# epochs = number of times to go through data

(6570083, 8628190)

In [26]:
model.wv.most_similar('daenerys')

[('targaryen', 0.7533897161483765),
 ('stormborn', 0.7389052510261536),
 ('princess', 0.6805124282836914),
 ('queen', 0.6751170754432678),
 ('elia', 0.661185622215271),
 ('viserys', 0.6529679298400879),
 ('myrcella', 0.6517089605331421),
 ('margaery', 0.6457107067108154),
 ('unburnt', 0.6422117352485657),
 ('rhaegar', 0.6412317156791687)]

In [29]:
model.wv.similarity('arya','sansa')

0.84674686

In [57]:
model.wv['deep'].shape

(100,)

In [58]:
vec = model.wv.get_normed_vectors()
# scaling up our vector to length 1 for consistency

In [59]:
vec

array([[-0.01647129, -0.08723932,  0.08451545, ..., -0.04201602,
        -0.03266841,  0.12788679],
       [-0.13973   , -0.08912255,  0.20364161, ..., -0.18031174,
         0.01330515,  0.06337025],
       [ 0.19833404, -0.02387944, -0.11048882, ..., -0.02553584,
         0.07390799, -0.13065566],
       ...,
       [-0.22201794,  0.13362008,  0.00634033, ..., -0.03306155,
         0.14367665, -0.03013193],
       [ 0.02235824,  0.07715704,  0.10468073, ...,  0.03175749,
         0.11953744, -0.0437912 ],
       [-0.11187262,  0.02322903,  0.04454752, ..., -0.02725858,
         0.04626405, -0.1151459 ]], dtype=float32)

In [60]:
from sklearn.decomposition import PCA
pca = PCA(n_components=3)
#reducing the dimenstion from 100 to 3 to picture it

In [61]:
X = pca.fit_transform(model.wv.get_normed_vectors())

In [62]:
X

array([[-0.14752363,  0.5952833 , -0.0939557 ],
       [-0.17963903,  0.34078866,  0.02818815],
       [ 0.2966655 ,  0.5614687 ,  0.18317255],
       ...,
       [-0.3859095 ,  0.04011524,  0.38402832],
       [-0.15249859,  0.10461047,  0.32242015],
       [ 0.07313119, -0.3321877 , -0.10913163]], dtype=float32)

In [63]:
X.shape

(17453, 3)

In [65]:
import plotly.express as px

words = model.wv.index_to_key  # list of words in the same order as X

fig = px.scatter_3d(
    x=X[200:300,0], y=X[200:300,1], z=X[200:300,2],
    text=words[200:300]   # show word on hover
)
fig.update_traces(marker=dict(size=4))
fig.show()

## **Text Classficiation Practical Using Machine Learning**

In [1]:
import os
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import re
import nltk
from nltk.corpus import stopwords
nltk.download('stopwords')
import string
from sklearn.model_selection import train_test_split
from sklearn.feature_extraction.text import CountVectorizer
from sklearn.feature_extraction.text import TfidfTransformer
from sklearn.metrics import confusion_matrix
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', 255)

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.


In [8]:
df = pd.read_csv('/content/drive/MyDrive/GenerativeAINotebooks/datasets/IMDB Dataset.csv', encoding='latin-1',names=["Review", "Sentiment"], header=None)
df.shape

(5686, 2)

In [7]:
df.head()

Review  \
0  narrative sublime. It's never included in critics' choices of Best Films but it should be. Still as poetic and powerful as when I first saw it over 17 years ago. I watch the 3 boxed sets every autumn for their 'mellow fruitfulness'. Inspired and inspi...   
1  Closer to reality and containing more depth than "Breakdance", Stan Lathan's "Beat Street" is still a pretty dull show. Again this pic is really only cashing in on the 'breakin' craze but at least we get a little bit of entertainment from the plot, wh...   
2  There are so many words I want to use to describe this movie, but can't really do that can I? This movie is a movie to watch if you just want to sit, laugh, cry and then pee. I'm serious. Don't watch this movie if you're easily offended by profanity, ...   
3  I cant describe how terrible this movie is. Am i the only one here who finds the way its animated totaly disgusting? The Men of Rohan look 100% fake with their poorly colored hair, that doesnt even come close to matching what the actors look like. The...   
4  Judging from this film and THE STRONG MAN, made the same year, I would not place Harry Langdon at the top of the list of great silent screen comedians. There simply is not enough there. Perhaps he was on his way to developing his style but sabotaged h...   

  Sentiment  
0  positive  
1  negative  
2  positive  
3  negative  
4  negative

In [9]:
df['Review'][0]

'narrative sublime. It\'s never included in critics\' choices of Best Films but it should be. Still as poetic and powerful as when I first saw it over 17 years ago. I watch the 3 boxed sets every autumn for their \'mellow fruitfulness\'. Inspired and inspiring."'

In [10]:
df['Sentiment'].value_counts() # Counting unique entities in a column

Sentiment
negative    2881
positive    2805
Name: count, dtype: int64

In [12]:
df.isnull().sum()  # for checking if there is any missing value

Review       0
Sentiment    0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(7)

In [14]:
df.drop_duplicates(inplace=True)

In [16]:
df.duplicated().sum()

np.int64(0)

### Performing basic pre processing
    - Remove tags-HTML
    - Lower case
    - stop words removing

In [17]:
df['Review'] = df['Review'].str.lower()

In [18]:
df['Review'][3]

'i cant describe how terrible this movie is. am i the only one here who finds the way its animated totaly disgusting? the men of rohan look 100% fake with their poorly colored hair, that doesnt even come close to matching what the actors look like. the orcs looked terrible. why does gandalf walk with a bad limp? why cant they pronounce things correctly? saruman isnt aruman. there were other what sounded like terrible pronounciation*sp* of tolkiens characters. all and all im glad the studio who made this pulled the plug out from the sequal, it was just a terrible terrible adaptaion. go watch the hobbit cartoon for a better cartoon of tolkiens work. hell, even the cartoon version of rotk is better then this dribble. 2/10'

In [19]:
import re
def remove_html_tags(text):
  pattern = re.compile('<.*?>')
  return pattern.sub(r'', text)

In [20]:
df['Review'] = df['Review'].apply(remove_html_tags)

In [21]:
def remove_stopwords(text):
    new_text = []

    for word in text.split():
        if word in stopwords.words('english'):
            new_text.append('')
        else:
            new_text.append(word)
    x = new_text[:]
    new_text.clear()
    return " ".join(x)

In [22]:
df['Review'] = df['Review'].apply(remove_stopwords)

In [24]:
df['Review'][0]

'narrative sublime.  never included  critics\' choices  best films    be. still  poetic  powerful    first saw   17 years ago.  watch  3 boxed sets every autumn   \'mellow fruitfulness\'. inspired  inspiring."'

In [25]:
X = df.iloc[:,0:1]
y = df['Sentiment']

In [26]:
X.head()

Review
0                                                   narrative sublime.  never included  critics' choices  best films    be. still  poetic  powerful    first saw   17 years ago.  watch  3 boxed sets every autumn   'mellow fruitfulness'. inspired  inspiring."
1  closer  reality  containing  depth  "breakdance", stan lathan's "beat street"  still  pretty dull show.   pic  really  cashing    'breakin' craze   least  get  little bit  entertainment   plot,  concerns  lives  three young friends   younger brother, ...
2     many words  want  use  describe  movie,  can't really    i?  movie   movie  watch    want  sit, laugh, cry   pee.  serious.  watch  movie   easily offended  profanity, sex, nudity, homosexuality...and everything else associated  nature.   woman,   ...
3   cant describe  terrible  movie is.     one   finds  way  animated totaly disgusting?  men  rohan look 100% fake   poorly colored hair,  doesnt even come close  matching   actors look like.  orcs looked terrible.   gandalf walk   bad limp?  cant  pron...
4  judging   film   strong man, made   year,  would  place harry langdon   top   list  great silent screen comedians.  simply   enough there. perhaps     way  developing  style  sabotaged   taking  first big successes  seriously.   event,    tricks  remi...

In [27]:
from sklearn.preprocessing import LabelEncoder
encoder = LabelEncoder()
y =encoder.fit_transform(y)

In [28]:
y

array([1, 0, 1, ..., 0, 0, 0])

In [32]:
X_train,X_test,Y_train, y_test = train_test_split(X,y , test_size=0.2, random_state=1)

In [33]:
X_train.shape

(4543, 1)

In [34]:
X_test.shape

(1136, 1)

In [37]:
# Applying Bag of words
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()

In [38]:
X_train_bow = cv.fit_transform(X_train['Review']).toarray()   # fit_tranform is used when we apply count vectorizer on training data
X_test_bow = cv.transform(X_test['Review']).toarray()         # transform is used when we apply count vectorizer on testing data

In [39]:
X_train_bow

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]])

In [40]:
from sklearn.naive_bayes import GaussianNB
gnb = GaussianNB()
gnb.fit(X_train_bow, Y_train)

GaussianNB()

In [41]:
y_pred = gnb.predict(X_test_bow)

from sklearn.metrics import accuracy_score
accuracy_score(y_test, y_pred)

0.613556338028169

In [42]:
confusion_matrix(y_test, y_pred)

array([[367, 190],
       [249, 330]])

In [43]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier()

rf.fit(X_train_bow,Y_train)

y_pred = rf.predict(X_test_bow)

accuracy_score(y_test,y_pred)

0.8195422535211268

In [46]:
cv = CountVectorizer(max_features=3000)  # max_features means we are taking 3000 frequent unique words

X_train_bow = cv.fit_transform(X_train['Review']).toarray()
X_test_bow = cv.transform(X_test['Review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,Y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)


0.8045774647887324

In [47]:
# USING N GRAMS
cv = CountVectorizer(ngram_range=(1,2),max_features=5000)

X_train_bow = cv.fit_transform(X_train['Review']).toarray()
X_test_bow = cv.transform(X_test['Review']).toarray()

rf = RandomForestClassifier()

rf.fit(X_train_bow,Y_train)
y_pred = rf.predict(X_test_bow)
accuracy_score(y_test,y_pred)

0.8213028169014085

In [49]:
# USING TF-IDF
from sklearn.feature_extraction.text import TfidfVectorizer
tfidf = TfidfVectorizer()

In [51]:
X_train_tfidf = tfidf.fit_transform(X_train['Review']).toarray()
X_test_tfidf = tfidf.transform(X_test['Review'])

In [52]:
rf = RandomForestClassifier()
rf.fit(X_train_tfidf,Y_train)
y_pred = rf.predict(X_test_tfidf)
accuracy_score(y_test,y_pred)

0.8098591549295775